In [13]:
import torch 

In [14]:
#configuration 
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
for i in range(torch.cuda.device_count()):
    print(torch.cuda.get_device_name())

NVIDIA GeForce RTX 3050 Laptop GPU


In [15]:
torch.manual_seed(42)

x_train = torch.linspace(0 , 10 , 100)
y_train = 2*x_train + 1 + torch.randn(100)  # y = 2x + 1 with noise 
x_train.shape , y_train.shape

(torch.Size([100]), torch.Size([100]))

In [16]:
#convert data to tensor and move them to the device 
x_train_tensor = x_train.view(-1 , 1 ).to(device)

y_train_tensor = y_train.view(-1 , 1 ).to(device)

In [17]:
# define tensors for the model parameters  and move them to the device 
torch.manual_seed(42)
b = torch.randn(1 , requires_grad= True , device= device  , dtype = torch.float)
w = torch.randn(1 , requires_grad = True , device = device , dtype = torch.float)
print(b , w)

tensor([0.1940], device='cuda:0', requires_grad=True) tensor([0.1391], device='cuda:0', requires_grad=True)


In [18]:
# compute the model prediction output 
yhat = b + w * x_train_tensor 

In [19]:
# computes the loss 
error = yhat - y_train_tensor 
# regression so  , using mean squared erro 
loss = (error**2).mean()
loss

tensor(133.6465, device='cuda:0', grad_fn=<MeanBackward0>)

In [20]:
# step 3 - compute the gradients for both b and w parameters 
# no more manual computation of the gradients 
loss.backward()

In [21]:
# onyl tensor  which where we set requires_grad can only be handel vai backward()  

GRAD 

In [22]:
# actuall values of the gradient  
b.grad

tensor([-20.3401], device='cuda:0')

In [23]:
w.grad

tensor([-133.2413], device='cuda:0')

## Zero , setp -4 

In [24]:
b

tensor([0.1940], device='cuda:0', requires_grad=True)

In [25]:
b.grad

tensor([-20.3401], device='cuda:0')

In [26]:
b.grad.zero_()

tensor([0.], device='cuda:0')

In [27]:
w.grad.zero_()

tensor([0.], device='cuda:0')

## Updating Parameter 

In [28]:
lr = 0.1 
torch.manual_seed(42)
w = torch.randn(1 , requires_grad= True , dtype = torch.float , device = device)
b = torch.randn(1, requires_grad = True , dtype = torch.float , device  = device)

# define number of epochs 
n_epochs = 100 



In [29]:
for epoch in range(n_epochs):
    yhat = b + w*x_train_tensor 

    #step - 2 
    error = yhat - y_train_tensor
    loss = (error**2).mean() 
    ########## 
    loss.backward()

    with torch.no_grad():
        b -= lr*b.grad
        w -= lr *w.grad

        b.grad.zero_() 
        w.grad.zero_() 
    print(b , w )




tensor([2.1292], device='cuda:0', requires_grad=True) tensor([13.2053], device='cuda:0', requires_grad=True)
tensor([-9.2900], device='cuda:0', requires_grad=True) tensor([-62.9535], device='cuda:0', requires_grad=True)
tensor([57.7335], device='cuda:0', requires_grad=True) tensor([382.5966], device='cuda:0', requires_grad=True)
tensor([-334.1979], device='cuda:0', requires_grad=True) tensor([-2224.2126], device='cuda:0', requires_grad=True)
tensor([1959.0663], device='cuda:0', requires_grad=True) tensor([13027.4092], device='cuda:0', requires_grad=True)
tensor([-11457.9434], device='cuda:0', requires_grad=True) tensor([-76205.2344], device='cuda:0', requires_grad=True)
tensor([67041.0781], device='cuda:0', requires_grad=True) tensor([445867.8750], device='cuda:0', requires_grad=True)
tensor([-392232.7500], device='cuda:0', requires_grad=True) tensor([-2608623.5000], device='cuda:0', requires_grad=True)
tensor([2294839.5000], device='cuda:0', requires_grad=True) tensor([15262278.], dev

In [30]:
b

tensor([nan], device='cuda:0', requires_grad=True)

In [31]:
b.grad

tensor([0.], device='cuda:0')