In [67]:
import torch 

In [68]:
#configuration 
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
for i in range(torch.cuda.device_count()):
    print(torch.cuda.get_device_name())

NVIDIA GeForce RTX 3050 Laptop GPU


In [69]:
torch.manual_seed(42)

x_train = torch.linspace(0 , 10 , 100)
y_train = 2*x_train + 1 + torch.randn(100)  # y = 2x + 1 with noise 
x_train.shape , y_train.shape

(torch.Size([100]), torch.Size([100]))

In [70]:
#convert data to tensor and move them to the device 
x_train_tensor = x_train.view(-1 , 1 ).to(device)

y_train_tensor = y_train.view(-1 , 1 ).to(device)

In [71]:
# define tensors for the model parameters  and move them to the device 
torch.manual_seed(42)
b = torch.randn(1 , requires_grad= True , device= device  , dtype = torch.float)
w = torch.randn(1 , requires_grad = True , device = device , dtype = torch.float)
print(b , w)

tensor([0.1940], device='cuda:0', requires_grad=True) tensor([0.1391], device='cuda:0', requires_grad=True)


In [84]:
# compute the model prediction output 
yhat = b + w * x_train_tensor 

In [85]:
# computes the loss 
error = yhat - y_train_tensor 
# regression so  , using mean squared erro 
loss = (error**2).mean()
loss

tensor(133.6465, device='cuda:0', grad_fn=<MeanBackward0>)

In [86]:
# step 3 - compute the gradients for both b and w parameters 
# no more manual computation of the gradients 
loss.backward()

In [87]:
# onyl tensor  which where we set requires_grad can only be handel vai backward()  

GRAD 

In [88]:
# actuall values of the gradient  
b.grad

tensor([-61.0204], device='cuda:0')

In [89]:
w.grad

tensor([-399.7238], device='cuda:0')

## Zero , setp -4 

In [90]:
b

tensor([0.1940], device='cuda:0', requires_grad=True)

In [92]:
b.grad

tensor([-61.0204], device='cuda:0')

In [93]:
b.grad.zero_()

tensor([0.], device='cuda:0')

In [102]:
w.grad.zero_()

tensor([0.], device='cuda:0')

## Updating Parameter 

In [104]:
lr = 0.1 
torch.manual_seed(42)
w = torch.randn(1 , requires_grad= True , dtype = torch.float , device = device)
b = torch.randn(1, requires_grad = True , dtype = torch.float , device  = device)

# define number of epochs 
n_epochs = 100 



In [110]:
for epoch in range(n_epochs):
    yhat = b + w*x_train_tensor 

    #step - 2 
    error = yhat - y_train_tensor
    loss = (error**2).mean() 
    ########## 
    loss.backward()

    with torch.no_grad():
        b -= lr*b.grad
        w -= lr *w.grad

        b.grad.zero_() 
        w.grad.zero_() 
    print(b , w )




tensor([5606.7456], device='cuda:0', requires_grad=True) tensor([29566.5605], device='cuda:0', requires_grad=True)
tensor([-25078.9512], device='cuda:0', requires_grad=True) tensor([-174131.6562], device='cuda:0', requires_grad=True)
tensor([154070.7188], device='cuda:0', requires_grad=True) tensor([1017702.5000], device='cuda:0', requires_grad=True)
tensor([-894443.7500], device='cuda:0', requires_grad=True) tensor([-5955303.], device='cuda:0', requires_grad=True)
tensor([5239750.], device='cuda:0', requires_grad=True) tensor([34841688.], device='cuda:0', requires_grad=True)
tensor([-30649882.], device='cuda:0', requires_grad=True) tensor([-2.0385e+08], device='cuda:0', requires_grad=True)
tensor([1.7933e+08], device='cuda:0', requires_grad=True) tensor([1.1927e+09], device='cuda:0', requires_grad=True)
tensor([-1.0492e+09], device='cuda:0', requires_grad=True) tensor([-6.9779e+09], device='cuda:0', requires_grad=True)
tensor([6.1385e+09], device='cuda:0', requires_grad=True) tensor([

In [106]:
b

tensor([0.1391], device='cuda:0', requires_grad=True)

In [107]:
b.grad

tensor([-1990.1093], device='cuda:0')