In [1]:
import torch 
import numpy as np
from torch.utils.tensorboard import SummaryWriter 


In [2]:
%run -i data_preparation/v2.py
%run -i model_configuration/v3.py
%run -i model_training/v5.py



In [4]:
#save 
#save 
checkpoint = {'epoch' : n_epochs , 
              'model_state_dict' : model.state_dict() , 
              'optimizer_state_dict': optimizer.state_dict() , 
              'loss': losses , 
              'val_loss' : val_losses}

checkpoint

{'epoch': 200,
 'model_state_dict': OrderedDict([('0.weight',
               tensor([[2.0392]], device='cuda:0')),
              ('0.bias', tensor([9.7361], device='cuda:0'))]),
 'optimizer_state_dict': {'state': {0: {'momentum_buffer': None},
   1: {'momentum_buffer': None}},
  'param_groups': [{'lr': 0.01,
    'momentum': 0,
    'dampening': 0,
    'weight_decay': 0,
    'nesterov': False,
    'maximize': False,
    'foreach': None,
    'differentiable': False,
    'fused': None,
    'params': [0, 1]}]},
 'loss': [18.321563720703125,
  15.284608840942383,
  12.605552673339844,
  14.131032943725586,
  10.50120735168457,
  13.305618286132812,
  13.559293746948242,
  10.164419174194336,
  11.771122932434082,
  8.442937850952148,
  10.343616485595703,
  9.65005874633789,
  9.756438255310059,
  12.474502563476562,
  7.038472652435303,
  7.063415050506592,
  5.952693462371826,
  4.232982635498047,
  7.292891502380371,
  9.461960792541504,
  5.070512771606445,
  7.919191360473633,
  6.74710

In [5]:
#save 
torch.save(checkpoint , 'model_checkpoint.pth') #creates model_checkpoint.pth file  pth = pytorch 


## we save  the checkpoint what about loadin it back 

In [6]:
# now run data prepreation and confifuration 
%run -i data_preparation/v2.py
%run -i model_configuration/v3.py

In [7]:
# check that we have untrain model
model.state_dict()

OrderedDict([('0.weight', tensor([[0.7645]], device='cuda:0')),
             ('0.bias', tensor([0.8300], device='cuda:0'))])

In [8]:

#load the dictionary back using torch.load()
#load model and optimizer state dictionaries back using load stae dict () 


In [9]:
checkpoint = torch.load('model_checkpoint.pth')#load the model
checkpoint

{'epoch': 200,
 'model_state_dict': OrderedDict([('0.weight',
               tensor([[2.0392]], device='cuda:0')),
              ('0.bias', tensor([9.7361], device='cuda:0'))]),
 'optimizer_state_dict': {'state': {0: {'momentum_buffer': None},
   1: {'momentum_buffer': None}},
  'param_groups': [{'lr': 0.01,
    'momentum': 0,
    'dampening': 0,
    'weight_decay': 0,
    'nesterov': False,
    'maximize': False,
    'foreach': None,
    'differentiable': False,
    'fused': None,
    'params': [0, 1]}]},
 'loss': [18.321563720703125,
  15.284608840942383,
  12.605552673339844,
  14.131032943725586,
  10.50120735168457,
  13.305618286132812,
  13.559293746948242,
  10.164419174194336,
  11.771122932434082,
  8.442937850952148,
  10.343616485595703,
  9.65005874633789,
  9.756438255310059,
  12.474502563476562,
  7.038472652435303,
  7.063415050506592,
  5.952693462371826,
  4.232982635498047,
  7.292891502380371,
  9.461960792541504,
  5.070512771606445,
  7.919191360473633,
  6.74710

In [10]:
checkpoint.keys()

dict_keys(['epoch', 'model_state_dict', 'optimizer_state_dict', 'loss', 'val_loss'])

In [11]:
checkpoint['model_state_dict']

OrderedDict([('0.weight', tensor([[2.0392]], device='cuda:0')),
             ('0.bias', tensor([9.7361], device='cuda:0'))])

In [12]:
model.load_state_dict(checkpoint['model_state_dict']) #load model  state dictionaries back using load state dict 
model.state_dict()

OrderedDict([('0.weight', tensor([[2.0392]], device='cuda:0')),
             ('0.bias', tensor([9.7361], device='cuda:0'))])

In [13]:
optimizer.load_state_dict(checkpoint['optimizer_state_dict']) #load optimizer state dict back using load state dict 


In [14]:
#laod every things into their corresponding values 
saved_epoch = checkpoint['epoch']
saved_loss =checkpoint['loss'] 
saved_val_losses = checkpoint['val_loss']



## now resume tranning form this check-point using model.train()
model.train()

In [15]:
model.train()

Sequential(
  (0): Linear(in_features=1, out_features=1, bias=True)
)

In [16]:
model.state_dict()

OrderedDict([('0.weight', tensor([[2.0392]], device='cuda:0')),
             ('0.bias', tensor([9.7361], device='cuda:0'))])

# up to here we have recover our model state and we can resume tranning 

In [17]:
 #now we can run our model_traning v5 which n_epochs  is 200 ; thus , our model will now again train for 200 epochs more from curerct epochs
current_epoch = saved_epoch
current_epoch

200

In [18]:
%run -i model_training/v5.py

In [19]:
model.state_dict()

OrderedDict([('0.weight', tensor([[2.0012]], device='cuda:0')),
             ('0.bias', tensor([9.9921], device='cuda:0'))])

the model we saved to disk was fully trainned model so we can use it for deploying / making prediction 


## Deploying / Making Prediction 

In [24]:
%run -i model_configuration/v3.py #once again we have untrain the model 

In [28]:
#recovering our model state 

checkpoint = torch.load('model_checkpoint.pth')
model.load_state_dict(checkpoint['model_state_dict'])
#since the mode is fully traned model to make prediction we dont need to load the optimizer or anything else 
model.state_dict() 



OrderedDict([('0.weight', tensor([[2.0392]], device='cuda:0')),
             ('0.bias', tensor([9.7361], device='cuda:0'))])

In [32]:
#making prediction in new inputs 
new_inputs = torch.tensor([[.20] , [.34] , [.57]])
model.eval() #always use eval for fully trained models 
model(new_inputs.to(device))

tensor([[10.1439],
        [10.4294],
        [10.8984]], device='cuda:0', grad_fn=<AddmmBackward0>)

## important 
# After checkpointing : model.train()
# after depolying/making_prediction : model.eval() 