In [1]:
import torch 
import torch.nn as nn


In [2]:
#cofiguration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [3]:
class ManualLinearRegression(nn.Module):
    def __init__(self):
        super().__init__()

        self.b = nn.Parameter(torch.randn(1 , 
                                          requires_grad= True ,  
                                          dtype = torch.float ))
        
        self.w = nn.Parameter(torch.randn(1 , requires_grad= True ,
                                          dtype = torch.float ))

    def forward(self ,x ):
        return self.b + self.w * x
    

In [4]:
torch.manual_seed(42)
dummy = ManualLinearRegression()
list(dummy.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [5]:
class ub(nn.Module):
    def __init__(self):
        super().__init__()

        self.b = nn.Parameter(torch.randn(1 , requires_grad = True , dtype = torch.float))
        self.w = nn.Parameter(torch.randn(1 , requires_grad = True  , dtype = torch.float))

    def forward(self, x ):
        return self.b + self.w * x 
    

In [6]:
torch.manual_seed(42)
dummy = ub()
list(dummy.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [7]:
## state_dict 
# curret values of all parameters 
dummy.state_dict()

OrderedDict([('b', tensor([0.3367])), ('w', tensor([0.1288]))])

In [8]:
# send our dummy model to a device 

torch.manual_seed(42)
dummy = ub().to(device)

In [9]:
# creating data 
x_train_tensor = torch.linspace(1 , 10 , 100 , dtype = torch.float ).to(device)
y_train_tensor = x_train_tensor * 2 + 1

In [10]:
lr = 0.01 

torch.manual_seed(42)
model = ManualLinearRegression().to(device)

optimizer = torch.optim.SGD(model.parameters() , lr = lr )

#define loss function 
loss_fn = nn.MSELoss(reduction= 'mean')

n_epochs = 100 
for epoch in range(n_epochs):
    model.train()
    #step - 1 
    yhat =  model(x_train_tensor)

    #step 2 - loss
    loss = loss_fn(yhat , y_train_tensor)

    #step 3 - computer gradients 
    loss.backward()

    #step - 4 update parameter using its state_dict 
    optimizer.step()
    optimizer.zero_grad()

print(model.state_dict())



OrderedDict([('b', tensor([0.7383], device='cuda:0')), ('w', tensor([2.0390], device='cuda:0'))])


In [11]:
linear = nn.Linear(1,1)

In [12]:
linear

Linear(in_features=1, out_features=1, bias=True)

In [13]:
linear.state_dict()

OrderedDict([('weight', tensor([[-0.2191]])), ('bias', tensor([0.2018]))])

In [14]:
model.parameters()

<generator object Module.parameters at 0x0000018A7324D0E0>

In [15]:
model.state_dict()


OrderedDict([('b', tensor([0.7383], device='cuda:0')),
             ('w', tensor([2.0390], device='cuda:0'))])

create  a same model with using linear(a , b) as paremeters


In [18]:
class MyLinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        #insed of our custom parameters , we use a linear Model
        self.linear = nn.Linear(1,1)

    def forward(self  , x  ):
        self.linear(x)


In [19]:
dummy = MyLinearRegression().to(device)
list(dummy.parameters())


[Parameter containing:
 tensor([[0.8815]], device='cuda:0', requires_grad=True),
 Parameter containing:
 tensor([-0.7336], device='cuda:0', requires_grad=True)]

<generator object Module.parameters at 0x00000192016E8900>

In [56]:

dummy.state_dict()

OrderedDict([('linear.weight', tensor([[0.7388]], device='cuda:0')),
             ('linear.bias', tensor([0.1354], device='cuda:0'))])

## sequential  Model 

In [58]:
torch.manual_seed(42)
model = nn.Sequential(nn.Linear(1 , 1 )).to(device)

In [61]:
# sequential model used when we have to condition like 
# output of the one model is input to anothers seris of model like simple neural  network 


In [63]:
torch.manual_seed(42)
model = nn.Sequential(nn.Linear(3,5) , nn.Linear(5,1)).to(device)
model.state_dict()

# here 3,5 means  - it is a hidden layer where it takes 3 input and 5 outputs
# 5 ,1  is output layer where 5,1 means  , it takes 5 inputs (i.e from previous hidden layer ) and give 1 output i.

OrderedDict([('0.weight',
              tensor([[ 0.4414,  0.4792, -0.1353],
                      [ 0.5304, -0.1265,  0.1165],
                      [-0.2811,  0.3391,  0.5090],
                      [-0.4236,  0.5018,  0.1081],
                      [ 0.4266,  0.0782,  0.2784]], device='cuda:0')),
             ('0.bias',
              tensor([-0.0815,  0.4451,  0.0853, -0.2695,  0.1472], device='cuda:0')),
             ('1.weight',
              tensor([[-0.2060, -0.0524, -0.1816,  0.2967, -0.3530]], device='cuda:0')),
             ('1.bias', tensor([-0.2062], device='cuda:0'))])

## add module to name the layers 


In [66]:
torch.manual_seed(42)
model = nn.Sequential()
model.add_module('Layer 1 ' , nn.Linear(3,5))
model.add_module('Layer 2 ' , nn.Linear(5,1))
model.to(device)
# now we have names of the linear module 

Sequential(
  (Layer 1 ): Linear(in_features=3, out_features=5, bias=True)
  (Layer 2 ): Linear(in_features=5, out_features=1, bias=True)
)