In [53]:
import torch
device  = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [68]:
#configuring data 
x_train_tensor = torch.linspace(0 , 10 , 100 , dtype= torch.float).to(device).view(-1 , 1 )
y_train_tensor = (x_train_tensor * 2  + 1).to(device).view(-1 , 1)

#parameters
w = torch.randn(1 , requires_grad= True ,  device= device , dtype = torch.float)
b = torch.randn(1, requires_grad= True ,  device = device , dtype = torch.float)



#define optimizer 
optimizer = torch.optim.SGD(params= [w , b ], lr = 0.01)
n_epochs =100
for epochs in range(n_epochs):
    yhat =  b + w * x_train_tensor

    #step - 2 compute looss
    error = (yhat - y_train_tensor)
    loss = (error **2).mean()

    #step-3 compute gradient for both b and w parameters
    loss.backward()

    #step -4 update parameters using gradients and the learning rate 
    # with torch.nograd():
    #   b-= lr * b.grad()
    #   w-=- lr * 2.grad()
    optimizer.step()
    optimizer.zero_grad()
print(b ,'\n' ,  w)
    



tensor([0.3489], device='cuda:0', requires_grad=True) 
 tensor([2.0979], device='cuda:0', requires_grad=True)


## loss 

In [69]:
loss_fn =   torch.nn.MSELoss(reduction= 'mean')
loss_fn

MSELoss()

In [75]:
torch.tensor((0.5 , 1.0))

tensor([0.5000, 1.0000])

In [76]:
prediction = torch.tensor((0.5 , 1.0 ))
labels = torch.tensor((2.0 , 1.3))
loss_fn(prediction , labels)

tensor(1.1700)

In [71]:
torch.tensor(2)

tensor(2)

In [40]:
n_epochs =100
for epochs in range(n_epochs):
    yhat =  

    #step - 2 compute looss
    error = (yhat - y_train_tensor)
    loss = (error **2).mean()

    #step-3 compute gradient for both b and w parameters
    loss.backward()

    #step -4 update parameters using gradients and the learning rate 
    # with torch.nograd():
    #   b-= lr * b.grad()
    #   w-=- lr * 2.grad()
    optimizer.step()
    optimizer.zero_grad()
print(b , w)
    



tensor([nan], device='cuda:0', requires_grad=True) tensor([nan], device='cuda:0', requires_grad=True)


In [80]:
## rewrite code implying loss function
lr = 0.01 
torch.manual_seed(0.1)
b = torch.randn(1  , requires_grad= True ,  dtype  = torch.float , device  = device ).to(device)
w = torch.randn(1 , requires_grad=  True , dtype = torch.float , device = device ).to(device)
# optimizer 
optimizer = torch.optim.SGD(params = [w , b] , lr = lr )

# define loss function 
loss_fn = torch.nn.MSELoss(reduction = 'mean')

epochs = 100 
for i in range(epochs):
    yhat = b + w * x_train_tensor 
    loss = loss_fn(yhat , y_train_tensor)

    # compute gradients for both  b and w 
    loss.backward()

    #step-4 update parameters using gradients 
    optimizer.step()
    optimizer.zero_grad()

print(b ,'\n' ,  w)
    

tensor([0.0184], device='cuda:0', requires_grad=True) 
 tensor([2.1476], device='cuda:0', requires_grad=True)


In [81]:

loss

tensor(0.2470, device='cuda:0', grad_fn=<MseLossBackward0>)

In [86]:
loss.detach()

tensor(0.2470, device='cuda:0')

In [87]:
loss


tensor(0.2470, device='cuda:0', grad_fn=<MseLossBackward0>)