In [1]:
import torch 

In [2]:
scaler = torch.tensor(12)
vector = torch.tensor([1,2,3])
matrix = torch.ones(2,3)

In [3]:
matrix

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
scaler.size

<function Tensor.size>

In [5]:
tensor = torch.randn(2  , 3, 4 )

In [6]:
tensor

tensor([[[-1.0159,  0.8782, -0.2787,  0.0970],
         [-1.2679,  0.6892,  0.6757,  1.5454],
         [-0.9524, -0.2177,  0.3641,  0.9086]],

        [[ 1.6076,  2.3000,  0.4569,  0.2900],
         [ 0.4837,  0.7790,  1.4518,  0.3678],
         [-1.0524, -2.3832, -0.4771,  0.0080]]])

In [7]:
tensor.size() 

torch.Size([2, 3, 4])

In [8]:
tensor.shape

torch.Size([2, 3, 4])

In [9]:
matrix.view(1,6)

tensor([[1., 1., 1., 1., 1., 1.]])

In [10]:
matrix.view(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
matrix.view(6 , 1 )

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [12]:
matrix.reshape(6 , 1 )

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [13]:
# clone or copy 
different_matrix = matrix.new_tensor(matrix.view(1 , 6 ))
different_matrix

C:\Users\Ujjwal\AppData\Local\Temp\ipykernel_17172\3400157964.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  different_matrix = matrix.new_tensor(matrix.view(1 , 6 ))


tensor([[1., 1., 1., 1., 1., 1.]])

In [14]:
a = matrix.view(1,6)

In [15]:
different_matrix[0,1] = 3 

In [16]:
matrix

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
a[0,1] = 3 

In [18]:
a

tensor([[1., 3., 1., 1., 1., 1.]])

In [19]:
matrix

tensor([[1., 3., 1.],
        [1., 1., 1.]])

In [20]:
matrix.view(1 , 6 ).clone().detach()

tensor([[1., 3., 1., 1., 1., 1.]])

In [21]:
import numpy as np

In [22]:
dummy_array = np.array([1 ,2 ,3])
dummy_tensor = torch.as_tensor(dummy_array)



In [23]:
#modifies the numpy array 
dummy_array[1] = 0 


In [24]:
# i have changed into dummy array but changes also happens into  , dummy tensor 
dummy_tensor

tensor([1, 0, 3], dtype=torch.int32)

In [25]:
dummy_array

array([1, 0, 3])

In [26]:
device = 'cuda' if torch.cuda.is_available else 'cpu'

In [27]:
torch.cuda.device_count()

1

In [28]:
for i in range(torch.cuda.device_count()):

    print(torch.cuda.get_device_name(i))

NVIDIA GeForce RTX 3050 Laptop GPU


In [29]:
x_train = np.random.randn(2 , 3 , 4 )

In [61]:
gpu_tensor = torch.as_tensor(x_train).to(device)
gpu_tensor 

tensor([[[ 0.3982, -0.7855, -0.4048,  1.8443],
         [ 1.2446, -0.3948, -1.2208,  0.6301],
         [ 0.9717, -0.5451, -1.0471,  0.2561]],

        [[ 0.2876, -1.5143, -0.5185, -1.2572],
         [-0.7298, -0.5901,  1.0634, -0.9813],
         [-0.8362, -1.8695,  2.2032, -0.2647]]], device='cuda:0',
       dtype=torch.float64)

In [62]:
torch.as_tensor(x_train).to('cpu')


tensor([[[ 0.3982, -0.7855, -0.4048,  1.8443],
         [ 1.2446, -0.3948, -1.2208,  0.6301],
         [ 0.9717, -0.5451, -1.0471,  0.2561]],

        [[ 0.2876, -1.5143, -0.5185, -1.2572],
         [-0.7298, -0.5901,  1.0634, -0.9813],
         [-0.8362, -1.8695,  2.2032, -0.2647]]], dtype=torch.float64)

In [33]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

array([[[-1.31784939, -0.51713161, -1.28272622, -0.76121453],
        [ 0.36244993, -0.95400724,  0.9543643 ,  0.439485  ],
        [ 2.29811408,  0.17624726,  0.64630396,  0.15053731]],

       [[ 0.00252102, -0.21185024, -1.97769828,  1.40676531],
        [ 1.05540739,  0.37796595, -0.47985738, -1.43197749],
        [ 1.40664501,  1.16049138, -0.21602451, -0.18584163]]])

In [38]:
x_train_tensor = torch.as_tensor(x_train).float().to(device)
y_train_tensor = torch.as_tensor(y_train).float().to(device)

In [39]:
x_train

array([[[-1.31784939, -0.51713161, -1.28272622, -0.76121453],
        [ 0.36244993, -0.95400724,  0.9543643 ,  0.439485  ],
        [ 2.29811408,  0.17624726,  0.64630396,  0.15053731]],

       [[ 0.00252102, -0.21185024, -1.97769828,  1.40676531],
        [ 1.05540739,  0.37796595, -0.47985738, -1.43197749],
        [ 1.40664501,  1.16049138, -0.21602451, -0.18584163]]])

### .type() is more usefull , because it tells where the tensor is (device)

In [44]:
print(type(x_train) , type(x_train_tensor) , x_train_tensor.type())

<class 'numpy.ndarray'> <class 'torch.Tensor'> torch.cuda.FloatTensor


In [51]:
## but .type() is only for pytorch tensor 
x_train.type()

AttributeError: 'numpy.ndarray' object has no attribute 'type'

### converting gpu tensor back to numpy

In [52]:
# one way you can do this 
x_train_tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [54]:
x = [1 , 2 ,3 ]
np.asarray(x)

array([1, 2, 3])

In [57]:
np.asarray(x_train_tensor)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [59]:
# unfortunatly numpy cannot handel gpu tensor , so we need to make them cpu tensor first using cpu()
x_train_tensor.cpu().numpy() 

array([[[-1.3178494 , -0.5171316 , -1.2827262 , -0.76121455],
        [ 0.36244994, -0.95400727,  0.9543643 ,  0.439485  ],
        [ 2.298114  ,  0.17624725,  0.64630395,  0.15053731]],

       [[ 0.00252102, -0.21185024, -1.9776983 ,  1.4067653 ],
        [ 1.0554074 ,  0.37796596, -0.4798574 , -1.4319775 ],
        [ 1.406645  ,  1.1604913 , -0.2160245 , -0.18584163]]],
      dtype=float32)

##  parameters 

In [67]:
# create two tensor for our parameters , including gradients and all , cpu tensor by defult
torch.manual_seed(42)
b = torch.randn(1 , requires_grad= True , dtype = torch.float)
w = torch.randn(1 , requires_grad= True , dtype = torch.float)
print(b , w )

tensor([0.3367], requires_grad=True) tensor([0.1288], requires_grad=True)


In [72]:
# WHAT IF WE WANT TO RUN GPU ? 
torch.manual_seed(42)
b = torch.randn(1,requires_grad= True , dtype = torch.float).to(device)
w = torch.randn( 1 , requires_grad = True , dtype = torch.float).to(device)
print(b , w )

tensor([0.3367], device='cuda:0', grad_fn=<ToCopyBackward0>) tensor([0.1288], device='cuda:0', grad_fn=<ToCopyBackward0>)


In [71]:
b.type()

'torch.cuda.FloatTensor'

In [73]:
# third we create regular tensor and sent them to gpu and then set  requires grad  
torch.manual_seed(42)
b = torch.randn(1 , dtype = torch.float)
w = torch.randn(1 , dtype = torch.float)
b.requires_grad_()
w.requires_grad_()
print(w , b)

tensor([0.1288], requires_grad=True) tensor([0.3367], requires_grad=True)
