In [2]:
import torch 

In [3]:
logits = torch.tensor([ 1.3863, 0.0000, -0.6931])


In [4]:
torch.exp(logits) # these are probabilities 

tensor([4.0000, 1.0000, 0.5000])

In [5]:
#expotentn of logis = odds ration

odds_ratio = torch.exp(logits)

In [6]:
odds_ratio

tensor([4.0000, 1.0000, 0.5000])

In [7]:
softmaxed = odds_ratio/odds_ratio.sum()
softmaxed

tensor([0.7273, 0.1818, 0.0909])

In [10]:
import torch.nn as nn

In [11]:
nn.Softmax(dim=-1)(logits)

tensor([0.7273, 0.1818, 0.0909])

In [12]:
nn.Softmax()(logits)

d:\software\miniconda\envs\mlenv\Lib\site-packages\torch\nn\modules\module.py:1532: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


tensor([0.7273, 0.1818, 0.0909])

In [16]:
import torch.nn.functional as F

In [19]:
torch.manual_seed(42)
dummy_logits= torch.randn((5,3))
dummy_lables= torch.tensor([0,0,1,2,1])
dummy_log_probs= F.log_softmax(input= dummy_logits, dim = -1)
dummy_log_probs

tensor([[-0.9988, -1.2067, -1.1011],
        [-0.6511, -2.0043, -1.0678],
        [-0.2090, -3.0552, -1.9555],
        [-1.3928, -1.1253, -0.8508],
        [-0.1684, -2.9684, -2.2676]])

In [20]:
dummy_logits

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890]])

In [22]:
loss_fn = nn.NLLLoss()
loss_fn(dummy_log_probs, dummy_lables)

tensor(1.7049)

In [23]:
log_probs = F.log_softmax(logits, dim= -1)
log_probs

tensor([-0.3185, -1.7048, -2.3979])

In [27]:
label = torch.tensor([2])
F.nll_loss(log_probs, label)

RuntimeError: size mismatch (got input: [3], target: [1])

In [40]:
F.nll_loss(log_probs.view(-1,3), label)


tensor(2.3979)

In [41]:
torch.manual_seed(11)
dummy_logits = torch.randn((5, 3))
dummy_labels = torch.tensor([0, 0, 1, 2, 1])
dummy_log_probs = F.log_softmax(dummy_logits, dim=-1)
dummy_log_probs

tensor([[-1.5229, -0.3146, -2.9600],
        [-1.7934, -1.0044, -0.7607],
        [-1.2513, -1.0136, -1.0471],
        [-2.6799, -0.2219, -2.0367],
        [-1.0728, -1.9098, -0.6737]])

In [42]:
loss_fn= nn.NLLLoss()
loss_fn(dummy_log_probs, dummy_lables)  

tensor(1.6553)

In [43]:
dummy_lables

tensor([0, 0, 1, 2, 1])

In [48]:
loss_fn = nn.NLLLoss(weight=torch.tensor([1., 1.,  2.]))
loss_fn(dummy_log_probs, dummy_labels)

tensor(1.7188)

In [47]:
dummy_labels.unique()

tensor([0, 1, 2])

In [50]:
loss_fn = nn.NLLLoss(ignore_index=2)(dummy_log_probs, dummy_lables)

In [51]:

loss_fn

tensor(1.5599)

In [53]:
dummy_log_probs.shape

torch.Size([5, 3])